### ISSUE TITLE
NPE in OtherPage of New Transformation Wizard

### ISSUE THREAD

**Issue by kcbabo** [fusesource/fuseide#190]
This one is a bit odd.  I was testing the New Transformation Wizard standalone (not through the palette extension) and when I first select it in the list of wizards when I choose File -> New -> Other -> Fuse Transformation and click Next, the following shows up in the Error Log:
```
java.lang.NullPointerException
	at org.jboss.tools.fuse.transformation.editor.internal.wizards.OtherPage.bindControls(OtherPage.java:253)
	at org.jboss.tools.fuse.transformation.editor.internal.wizards.OtherPage.createPage(OtherPage.java:214)
	at org.jboss.tools.fuse.transformation.editor.internal.wizards.OtherPage.access$0(OtherPage.java:127)
	at org.jboss.tools.fuse.transformation.editor.internal.wizards.OtherPage$1.run(OtherPage.java:118)
	at org.eclipse.core.databinding.observable.ObservableTracker.runAndCollect(ObservableTracker.java:150)
	at org.eclipse.core.databinding.ObservablesManager.runAndCollect(ObservablesManager.java:103)
	at org.jboss.tools.fuse.transformation.editor.internal.wizards.OtherPage.createControl(OtherPage.java:114)
	at org.eclipse.jface.wizard.Wizard.createPageControls(Wizard.java:178)
```

**Comment by kcbabo** [comment]
BTW, I can move past this by clicking Next again, but the wizard ends up in a bad state.  Page 2 asks for Java source class when I entered XML as the source type.

**Comment by bfitzpat** [comment]
Issued PR - https://github.com/fusesource/fuseide/pull/194

**Comment by bfitzpat** [comment]
Keith, I have to run but let me know if you run into any issues with these changes

**Comment by kcbabo** [comment]
closed with https://github.com/fusesource/fuseide/pull/196
