### ISSUE TITLE
Unable to delete mappings when Set Field used

### ISSUE THREAD

**Issue by kcbabo** [fusesource/fuseide#207]
1) Create an empty mapping.
2) In the detail view, use the drop-down menu "Set Field" to select the source and target fields.
3) Try to remove the new mapping ... BOOM!

Error message is "Widget is disposed". Stack trace:
```
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4441)
	at org.eclipse.swt.SWT.error(SWT.java:4356)
	at org.eclipse.swt.SWT.error(SWT.java:4327)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:783)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:573)
	at org.eclipse.swt.widgets.Tree.getSelection(Tree.java:1753)
	at org.eclipse.jface.viewers.TreeViewer.getSelection(TreeViewer.java:232)
	at org.eclipse.jface.viewers.TreeViewer.setSelection(TreeViewer.java:311)
	at org.eclipse.jface.viewers.AbstractTreeViewer.setSelectionToWidget(AbstractTreeViewer.java:2547)
	at org.eclipse.jface.viewers.AbstractTreeViewer.setSelectionToWidget(AbstractTreeViewer.java:2974)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1443)
	at org.eclipse.jface.viewers.TreeViewer.preservingSelection(TreeViewer.java:366)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1397)
	at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1497)
	at org.eclipse.jface.viewers.ColumnViewer.refresh(ColumnViewer.java:521)
	at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1456)
	at org.jboss.tools.fuse.transformation.editor.internal.ModelViewer$9.propertyChange(ModelViewer.java:264)
	at org.jboss.tools.fuse.transformation.editor.internal.util.TransformationConfig.fireEvent(TransformationConfig.java:155)
	at org.jboss.tools.fuse.transformation.editor.internal.util.TransformationConfig.mapField(TransformationConfig.java:287)
	at org.jboss.tools.fuse.transformation.editor.TransformationEditor$TargetModelTabFolder$1TargetModelViewer$1.performDrop(TransformationEditor.java:352)
	at org.eclipse.jface.viewers.ViewerDropAdapter.drop(ViewerDropAdapter.java:254)
```

**Comment by bfitzpat** [comment]
Found the culprit - fixed in this PR - https://github.com/fusesource/fuseide/pull/211
