### ISSUE TITLE
Error in new transformation wizard when dataFormat is missing it attribute

### ISSUE THREAD

**Issue by kcbabo** [fusesource/fuseide#222]
Let's say I have an existing dataFormat defined in my Camel Context, but it doesn't have an id, e.g.
```
<dataFormats>
    <jaxb contextPath="foo"/>
</dataFormats>
```

This creates problems in the new transformation wizard when Other is selected as a source/target type:
```
org.eclipse.core.runtime.AssertionFailedException: null argument:
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:85)
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:73)
	at org.eclipse.jface.viewers.StructuredViewer.assertElementsNotNull(StructuredViewer.java:584)
	at org.eclipse.jface.viewers.StructuredViewer.getRawChildren(StructuredViewer.java:1000)
	at org.eclipse.jface.viewers.StructuredViewer.getFilteredChildren(StructuredViewer.java:905)
	at org.eclipse.jface.viewers.StructuredViewer.getSortedChildren(StructuredViewer.java:1057)
	at org.eclipse.jface.viewers.AbstractListViewer.inputChanged(AbstractListViewer.java:318)
	at org.eclipse.jface.viewers.ContentViewer.setInput(ContentViewer.java:292)
	at org.eclipse.jface.viewers.StructuredViewer.setInput(StructuredViewer.java:1675)
	at org.jboss.tools.fuse.transformation.editor.internal.wizards.OtherPage.initialize(OtherPage.java:270)
	at org.jboss.tools.fuse.transformation.editor.internal.wizards.OtherPage.setVisible(OtherPage.java:353)
	at org.eclipse.jface.wizard.WizardDialog.updateForPage(WizardDialog.java:1289)
	at org.eclipse.jface.wizard.WizardDialog.access$4(WizardDialog.java:1268)
	at org.eclipse.jface.wizard.WizardDialog$8.run(WizardDialog.java:1257)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.jface.wizard.WizardDialog.showPage(WizardDialog.java:1254)
	at org.eclipse.jface.wizard.WizardDialog.nextPressed(WizardDialog.java:942)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:434)
	at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:619)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4199)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1467)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1490)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1475)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1279)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4042)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3669)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:832)
	at org.eclipse.jface.window.Window.open(Window.java:808)
	at org.jboss.tools.fuse.transformation.extensions.DataTransformationPaletteEntry$DataMapperEndpointFigureFeature.createNode(DataTransformationPaletteEntry.java:168)
	at org.jboss.tools.fuse.transformation.extensions.DataTransformationPaletteEntry$DataMapperEndpointFigureFeature.create(DataTransformationPaletteEntry.java:121)
```

**Comment by bfitzpat** [comment]
this PR - https://github.com/fusesource/fuseide/pull/225 - takes care of it along with the typo in #223

**Comment by kcbabo** [comment]
pushed
