### ISSUE TITLE
NPE in transformation id validation

### ISSUE THREAD

**Issue by kcbabo** [fusesource/fuseide#224]
Launch the Fuse Transformation wizard via the New menu instead of dragging an endpoint onto the canvas.  When you enter the transformation id, you'll see lots of validation errors in the error log:

```
java.lang.NullPointerException
	at org.jboss.tools.fuse.transformation.editor.internal.wizards.StartPage$9.validate(StartPage.java:334)
	at org.eclipse.core.databinding.UpdateValueStrategy.validateBeforeSet(UpdateValueStrategy.java:473)
	at org.eclipse.core.databinding.ValueBinding$3.run(ValueBinding.java:180)
	at org.eclipse.core.databinding.observable.Realm$1.run(Realm.java:148)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.databinding.observable.Realm.safeRun(Realm.java:152)
	at org.eclipse.core.databinding.observable.Realm.exec(Realm.java:170)
	at org.eclipse.core.databinding.ValueBinding.doUpdate(ValueBinding.java:151)
	at org.eclipse.core.databinding.ValueBinding.validateTargetToModel(ValueBinding.java:234)
	at org.eclipse.core.databinding.ValueBinding.postInit(ValueBinding.java:103)
	at org.eclipse.core.databinding.Binding.init(Binding.java:79)
	at org.eclipse.core.databinding.DataBindingContext.bindValue(DataBindingContext.java:167)
	at org.jboss.tools.fuse.transformation.editor.internal.wizards.StartPage.bindControls(StartPage.java:343)
	at org.jboss.tools.fuse.transformation.editor.internal.wizards.StartPage.createPage(StartPage.java:207)
	at org.jboss.tools.fuse.transformation.editor.internal.wizards.StartPage.access$0(StartPage.java:100)
	at org.jboss.tools.fuse.transformation.editor.internal.wizards.StartPage$1.run(StartPage.java:92)
	at org.eclipse.core.databinding.observable.ObservableTracker.runAndCollect(ObservableTracker.java:150)
	at org.eclipse.core.databinding.ObservablesManager.runAndCollect(ObservablesManager.java:103)
	at org.jboss.tools.fuse.transformation.editor.internal.wizards.StartPage.createControl(StartPage.java:88)
	at org.eclipse.jface.wizard.Wizard.createPageControls(Wizard.java:178)
	at org.eclipse.jface.wizard.WizardDialog.createPageControls(WizardDialog.java:759)
	at org.eclipse.jface.wizard.WizardDialog.setWizard(WizardDialog.java:1210)
	at org.eclipse.jface.wizard.WizardDialog.updateForPage(WizardDialog.java:1271)
```

**Comment by bfitzpat** [comment]
I have tried everything I can do to repro this with the latest code and can't. Any additional details would be fantastic. :)

**Comment by kcbabo** [comment]
Cannot reproduce - so closing.
