### ISSUE TITLE
Exception when using any type of expression mapping

### ISSUE THREAD

**Issue by kcbabo** [fusesource/fuseide#251]
Try to use any type of expression mapping and you'll hit this:
```
!STACK 0
java.lang.ClassCastException: org.jboss.tools.fuse.transformation.dozer.DozerExpression cannot be cast to org.jboss.tools.fuse.transformation.model.Model
	at org.jboss.tools.fuse.transformation.editor.internal.MappingSummary.configEvent(MappingSummary.java:124)
	at org.jboss.tools.fuse.transformation.editor.internal.MappingSummary$2.propertyChange(MappingSummary.java:111)
	at org.jboss.tools.fuse.transformation.editor.internal.util.TransformationConfig.fireEvent(TransformationConfig.java:155)
	at org.jboss.tools.fuse.transformation.editor.internal.util.TransformationConfig.update(TransformationConfig.java:525)
	at org.jboss.tools.fuse.transformation.editor.internal.util.TransformationConfig.setSourceExpression(TransformationConfig.java:439)
	at org.jboss.tools.fuse.transformation.editor.internal.MappingDetailViewer.setExpression(MappingDetailViewer.java:314)
	at org.jboss.tools.fuse.transformation.editor.internal.MappingDetailViewer$3$3.widgetSelected(MappingDetailViewer.java:229)
```

**Comment by kcbabo** [comment]
Looks like this regressed when the drag-drop validation was added.  MappingSummary:124 assumes that the source field is always a model, but that is not true for variables and expressions.

**Comment by jpav** [comment]
Assigning this back to @bfitzpat since I didn't realize this is due to the new validation additions, which I know he's currently working on still.

**Comment by bfitzpat** [comment]
Here's a PR for this one... https://github.com/fusesource/fuseide/pull/260

**Comment by kcbabo** [comment]
pushed
