### ISSUE TITLE
Transformation Test wizard broken

### ISSUE THREAD

**Issue by kcbabo** [fusesource/fuseide#253]
Getting "Problem encountered while creating test class" when trying to finish the wizard:
```
Java Model Exception: Core Exception [code 0] Problem encountered while creating test class.
	at org.eclipse.jdt.internal.core.BatchOperation.executeOperation(BatchOperation.java:50)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:729)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2313)
	at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:5358)
	at org.eclipse.jdt.internal.ui.actions.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:106)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: org.eclipse.core.runtime.CoreException: Problem encountered while creating test class.
	at org.jboss.tools.fuse.transformation.editor.wizards.NewTransformationTestWizard.finishPage(NewTransformationTestWizard.java:163)
	at org.eclipse.jdt.internal.ui.wizards.NewElementWizard$2.run(NewElementWizard.java:118)
	at org.eclipse.jdt.internal.core.BatchOperation.executeOperation(BatchOperation.java:39)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:729)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2313)
	at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:5358)
	at org.eclipse.jdt.internal.ui.actions.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:106)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by kcbabo** [comment]
This line is returning null:
https://github.com/fusesource/fuseide/blob/master/transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/wizards/TransformTestWizardPage.java#L254

**Comment by bfitzpat** [comment]
@kcbabo - Can you provide some repro steps? I walked through specifying a project, selecting a camel config, etc, and it worked for me - but I suspect I'm staying on the happy path.

**Comment by kcbabo** [comment]
@bfitzpat - hacking around a bit and this fixes the issue for me:
https://github.com/kcbabo/fuseide/commit/8253baffcf2cbdfd6353d55ddfb5466ff40f95cb

**Comment by bfitzpat** [comment]
Created a PR https://github.com/fusesource/fuseide/pull/255

**Comment by kcbabo** [comment]
pushed
