### ISSUE TITLE
ClassCastException when project has bad Maven config

### ISSUE THREAD

**Issue by kcbabo** [fusesource/fuseide#308]
If a Fuse project cannot build (e.g. due to bad Maven config), then the Fuse Transformation wizard fails with the exception below.  I originally though this was due to something else, but I can reproduce it reliably when a Maven dependency in the POM has an incorrect version string.

```

java.lang.ClassCastException: org.jboss.tools.fuse.transformation.dozer.config.FieldDefinition$JaxbAccessorF_content cannot be cast to com.sun.xml.internal.bind.v2.runtime.reflect.Accessor
	at com.sun.xml.internal.bind.v2.runtime.reflect.opt.OptimizedAccessorFactory.instanciate(OptimizedAccessorFactory.java:190)
	at com.sun.xml.internal.bind.v2.runtime.reflect.opt.OptimizedAccessorFactory.get(OptimizedAccessorFactory.java:179)
	at com.sun.xml.internal.bind.v2.runtime.reflect.Accessor$FieldReflection.optimize(Accessor.java:271)
	at com.sun.xml.internal.bind.v2.runtime.reflect.TransducedAccessor$CompositeTransducedAccessorImpl.<init>(TransducedAccessor.java:220)
	at com.sun.xml.internal.bind.v2.runtime.reflect.TransducedAccessor.get(TransducedAccessor.java:160)
	at com.sun.xml.internal.bind.v2.runtime.property.ValueProperty.<init>(ValueProperty.java:66)
	at com.sun.xml.internal.bind.v2.runtime.property.PropertyFactory.create(PropertyFactory.java:95)
	at com.sun.xml.internal.bind.v2.runtime.ClassBeanInfoImpl.<init>(ClassBeanInfoImpl.java:166)
	at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.getOrCreate(JAXBContextImpl.java:488)
	at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:305)
	at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:124)
	at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1123)
	at com.sun.xml.internal.bind.v2.ContextFactory.createContext(ContextFactory.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:247)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:234)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:462)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:641)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:584)
	at org.jboss.tools.fuse.transformation.dozer.DozerMapperConfiguration.getJAXBContext(DozerMapperConfiguration.java:472)
	at org.jboss.tools.fuse.transformation.dozer.DozerMapperConfiguration.saveConfig(DozerMapperConfiguration.java:308)
	at org.jboss.tools.fuse.transformation.editor.wizards.NewTransformationWizard$1.run(NewTransformationWizard.java:175)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:466)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:374)
	at org.eclipse.jface.wizard.WizardDialog.run(WizardDialog.java:1059)
	at org.jboss.tools.fuse.transformation.editor.wizards.NewTransformationWizard.performFinish(NewTransformationWizard.java:224)
```

**Comment by ruslan5t** [comment]
Any solution?

**Comment by apupier** [comment]
@ruslan5t the issue has been closed 2 years ago. it should be fixed.
Do you encounter the same kind of issue? Can you provide the new stacktrace (lines has surely changed)?

**Comment by ruslan5t** [comment]
Hi @apupier. It was bug in my application, so it caused same exception. Never mind.
